from sqlalchemy import Column, Integer, String, Boolean, Date
from app.db.base import Base

class LoanApplication(Base):
    __tablename__ = "loan_applications"

    id = Column(Integer, primary_key=True, index=True)
    responsible_name = Column(String)
    responsible_cpf = Column(String)
    full_name = Column(String)
    birth_date = Column(String)
    cpf_number = Column(String)
    rg_number = Column(String)
    mother_name = Column(String)
    father_name = Column(String)
    marital_status = Column(String)
    spouse_name = Column(String)
    spouse_cpf = Column(String)
    zipcode = Column(String)
    address = Column(String)
    address_number = Column(String)
    address_complement = Column(String)
    neighborhood = Column(String)
    city = Column(String)
    phone = Column(String)
    email = Column(String)
    occupation = Column(String)
    job_title = Column(String)
    company_name = Column(String)
    employer_cnpj = Column(String)
    hire_date = Column(String)
    gross_monthly_income = Column(String)
    additional_income = Column(String)
    income_source = Column(String)
    income_description = Column(String)
    license_plate_loan = Column(String)
    vehicle_type = Column(String)
    vehicle_model = Column(String)
    vehicle_year = Column(String)
    purchase_value = Column(String)
    loan_amount = Column(String)
    installments = Column(String)
    vehicle_year_fab = Column(String)
