from sqlalchemy import Column, Integer, String
from app.db.base import Base

class LoanApplicationPJ(Base):
    __tablename__ = "loan_applications_pj"

    id = Column(Integer, primary_key=True, index=True)
    company_cnpj = Column(String)
    company_name = Column(String)
    trade_name = Column(String)
    company_incorporation_date = Column(String)
    company_economic_activity = Column(String)
    company_billing_group = Column(String)
    company_share_control = Column(String)
    zipcode = Column(String)
    address = Column(String)
    address_number = Column(String)
    address_complement = Column(String)
    neighborhood = Column(String)
    city = Column(String)
    state = Column(String)
    country = Column(String)
    phone = Column(String)
    fax = Column(String)
    website = Column(String)
    email = Column(String)
    responsible_name = Column(String)
    responsible_cpf = Column(String)
    responsible_rg = Column(String)
    responsible_birthdate = Column(String)
    responsible_father = Column(String)
    responsible_mother = Column(String)
    marital_status = Column(String)
    spouse_name = Column(String)
    spouse_cpf = Column(String)
    license_plate = Column(String)
    vehicle_type = Column(String)
    vehicle_model = Column(String)
    installments = Column(String)
    vehicle_year = Column(String)
    vehicle_year_fab = Column(String)
    purchase_value = Column(String)
    loan_amount = Column(String)
